##CONFIG for Data preprocessing CNN 

# Nominal ENF
nominal_enf: 50.0       # Expected ENF frequency in Hz

# Windowing
window_type: 'hann'


# Downsampling
downsample_enabled: true
downsampling_frequency_per_nominal_enf: 20


# Bandpass Filter Configuration
bandpass_filter:
  is_enabled: true
  lowcut: 49.5    # Low cut frequency in Hz
  highcut: 50.5   # High cut frequency in Hz
  order: 1


# Variational Mode Decomposition (VMD)
VMD: 
  is_enabled: true
  loop: 5              # Number of VMD iterations
  alpha: 5000          # Balancing parameter of the data-fidelity constraint
  tau: 0               # Noise-tolerance (no strict fidelity enforcement)
  n_mode: 1            # Number of modes to be recovered
  DC: false            # True if the first mode is to be DC (0-freq)
  tol: !!float 1e-7    # Tolerance of convergence criterion


# Robust Filtering Algorithm (RFA)
RFA: 
  is_enabled: true
  f0: 50                   # estimated frequency (here ENF second harmonic)     
  I: 3                      # Number of RFA repeats
  tau: 1000                # RFA winoow size
  epsilon: !!float 1e-20    # Noise-tolerance (no strict fidelity enforcement)


# Phase Estimation Configuration
phase_estimation:
  n_dft: 20000             # Number of points in DFT for phase estimation
  step_size: 20            # Step Size
  window_len: 200          # Window Length


# Freq Estimation Configuration
freq_estimation:
  n_dft: 20_000             # Number of points in DFT for phase estimation
  step_size: 20             # Step Size
  window_len: 200           # Window Length


# Plot Results
plot_results:
  is_enabled: true         # TODO: Switch not used yet.
